"""config to store constant variables for liquidity monitor script"""
import datetime

FRED_API_KEY = ""

PREV_QT_START = datetime.datetime(2017, 10, 1)
PREV_QT_END = datetime.datetime(2019, 7, 31)
QT_START = datetime.datetime(2022, 6, 1)
QT_END = None

TS_START_DATE = datetime.datetime(2017, 1, 1)
TS_START_DATE_L = datetime.datetime(2018, 4, 2)

HOST = "34.148.149.200"
USER = "maxentropy_user"
PWD = "maxentropy_user"

DATABASE_STIR = "STIR_DB"
TABLE_FF_DECOMP_VOLUME = "TABLE_FF_DECOMP_VOLUME"
TABLE_RESERVE_BALANCE = "TABLE_RESERVE_BALANCE"
TABLE_IORB = "TABLE_IORB"
TABLE_EFFR = "TABLE_EFFR"
TABLE_UPPER_BOUND = "TABLE_UPPER_BOUND"
TABLE_LOWER_BOUND = "TABLE_LOWER_BOUND"
TABLE_RRP_RATE = "TABLE_RRP_RATE"
TABLE_RRP_VOLUME = "TABLE_RRP_VOLUME"
TABLE_FOREIGN_RRP = "TABLE_FOREIGN_RRP"
TABLE_TGA_BALANCE = "TABLE_TGA_BALANCE"
TABLE_OFR_ON_DATA = "TABLE_OFR_ON_DATA"
TABLE_DAYLIGHT_OVERDFRAT = "TABLE_DAYLIGHT_OVERDFRAT"
TABLE_ELASTICITY = "TABLE_ELASTICITY"
